services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: startup_app
    restart: unless-stopped
    volumes:
      - storage:/var/www/storage
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: startup
      DB_USERNAME: sa
      DB_PASSWORD: secret
      REDIS_HOST: redis
    networks:
      - net

  # node:
  #   build:
  #     context: .
  #     dockerfile: docker/node/Dockerfile
  #   container_name: startup-node
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - "5173:5173" # Vite dev server
  #   command: [ "npm", "run", "dev" ]
  #   networks:
  #     - net

  nginx:
    image: nginx:alpine
    container_name: startup_nginx
    restart: unless-stopped
    ports:
      - "9992:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - net

  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: secret
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  mysql:
    image: mysql:8.0
    container_name: startup_mysql
    restart: unless-stopped
    ports:
      - "6033:3306" # MySQL uses port 3306
    environment:
      MYSQL_DATABASE: startup
      MYSQL_USER: sa
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret # Required by MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net

  redis:
    image: redis:alpine
    container_name: startup_redis
    ports:
      - "6380:6379"
    networks:
      - net

volumes:
  mysql_data:
  storage:


networks:
  net:
    driver: bridge
